import { Project } from "@/types/content";

export const projects: Project[] = [
  {
    id: "auto-schema-pipeline",
    title: "Auto Schema Pipeline",
    timeframe: "2026 – Present",
    status: "live",
    stack: ["Python", "FastAPI", "PostgreSQL", "Docker", "Gemini API", "Embeddings"],
    description:
      "Automatically infers a CSV's data schema on upload and uses the Gemini API to generate precise SQL queries from the detected patterns, removing the need for manual query writing and surfacing insights through an integrated dashboard and generated PDF reports.",
    links: {
      repo: "https://github.com/parthrshah202-hash/auto-schema-pipeline",
      demo: "https://auto-schema-pipeline.streamlit.app/",
    },
  },
  {
    id: "universal-data-ingestion",
    title: "Universal Data Ingestion",
    timeframe: "2026 – Present",
    status: "in-progress",
    stack: ["Python", "LLMs", "RAG", "Vector Databases", "Embeddings"],
    description:
      "A universal ingestion pipeline that classifies and normalizes unstructured and semi-structured files (PDFs, spreadsheets, UPI exports) using ML-driven document classification and dynamic column mapping, targeting a containerized, cloud-deployed system with versioned PostgreSQL schemas.",
    links: {},
  },
  {
    id: "confidence-detection-llms",
    title: "Confidence Detection for LLMs",
    timeframe: "2025 – Present",
    status: "research",
    stack: ["Python", "Machine Learning", "NLP", "LLM Evaluation"],
    description:
      "A research project exploring how to estimate the confidence of responses generated by large language models, aiming to flag uncertain or likely-incorrect outputs and improve the trustworthiness of AI systems.",
    links: {},
  },
  {
    id: "ai-coding-mentor",
    title: "AI Coding Mentor",
    timeframe: "2026",
    status: "live",
    stack: ["Python", "Streamlit", "Gemini API"],
    description:
      "An AI-powered DSA hint engine that gives students guided hints and explanations instead of direct solutions, encouraging independent problem-solving.",
    links: {
      repo: "https://github.com/parthrshah202-hash/DSA_MENTOR",
      demo: "https://dsamentor.streamlit.app/",
    },
  },
  {
    id: "log-data-pipeline",
    title: "Log Data Pipeline",
    timeframe: "2026",
    status: "live",
    stack: ["Python", "Streamlit"],
    description:
      "A four-stage pipeline — ingestion, transformation, analysis, and visualization — that turns raw server logs into an interactive dashboard with nine charts and automated insight reports. Built as a freshman project to learn data engineering fundamentals.",
    links: {
      repo: "https://github.com/parthrshah202-hash/log-data-pipeline",
      demo: "https://log-data-pipeline-3aicicf8mzcz2k2e2k4uch.streamlit.app/",
    },
  },
];
